http_server:
  port: 8080


mysql:
  username: root
  password: 123
  port: 3306
  host: localhost
  db_name: expensetracker 

auth:
  sign_key: "your-secret-key-change-in-production"



logger:
  file_path: "logs/app.log"
  use_local_time: false        # false = UTC, true = local time
  file_max_size_mb: 100        # megabytes
  file_max_age_days: 30        # days to keep
  max_backups: 5               # number of old log files
  compress: true               # compress rotated logs


